title: Ryan
description: Book reviews, CS180 projects, and the MRI DeCal.
url: "https://rYan-theusername.github.io"
baseurl: "/rYan_the_username"

permalink: pretty
markdown: kramdown

collections:
  reviews:
    output: true
    permalink: /reviews/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: reviews
    values:
      layout: review

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - .github
